### ISSUE TITLE
Error parsing logs (slice bounds out of range)

### ISSUE THREAD

**Issue by mtheofy** [menandmice-services/logeater#1]
Hello,

I compiled the tools but every time I try to run it I get an error. I am trying to parse logs generated by named 9.16.7 running on a Raspberry Pi.

```cat query.log | /usr/local/bin/logeater-resolvers
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main()
 /root/logeater/logeater-resolvers.go:47 +0x228
```
I do not speak "go" to fix it :(

thanks

**Comment by cstrotm** [comment]
Thanks for the report. I will check this later today and see if I can fix the issue.

**Comment by cstrotm** [comment]
@mtheophy 

I've just tested logeater-resolver on a current BIND 9 logfile with no errors.

From your example, you pipe a query-log file to logeater-resolvers. That will not work. The logfile has a different format and cannot be parsed by logeater-resolvers, but by logeater-queries. Can you check if logeater-queries works on your query log file?

**Comment by mtheofy** [comment]
> 
> 
> @mtheophy
> 
> I've just tested logeater-resolver on a current BIND 9 logfile with no errors.
> 
> From your example, you pipe a query-log file to logeater-resolvers. That will not work. The logfile has a different format and cannot be parsed by logeater-resolvers, but by logeater-queries. Can you check if logeater-queries works on your query log file?

good catch! Nevertheless, I tried with the correct utility and got a similar error

```cat query.log | /usr/local/bin/logeater-queries
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main()
        /root/logeater/logeater-queries.go:73 +0x1334```

Just wondering. Does the utility expect a specific level of logging to parse the log file correctly?

**Comment by cstrotm** [comment]
@mtheophy 

My query.log format looks like this

```
14-Jun-2020 15:19:20.548 client @0x498b14e8 172.217.33.131#47687 (ns5.tidelock.de): query: ns5.tidelock.de IN AAAA -E(0) (5.45.109.212) [ECS 94.247.116.0/24/0]
14-Jun-2020 15:19:20.613 client @0x498b14e8 172.217.34.4#41507 (ns4.tidelock.de): query: ns4.tidelock.de IN AAAA -E(0) (5.45.109.212) [ECS 94.247.116.0/24/0]
14-Jun-2020 15:19:21.134 client @0x498b14e8 172.217.44.1#41246 (ns8.dnssec.works): query: ns8.dnssec.works IN A -E(0) (5.45.109.212) [ECS 144.168.164.0/24/0]
14-Jun-2020 15:19:21.135 client @0x6c70a4e8 172.217.44.1#43952 (ns8.dnssec.works): query: ns8.dnssec.works IN AAAA -E(0) (5.45.109.212) [ECS 144.168.164.0/24/0]
14-Jun-2020 15:19:21.195 client @0x6c70a4e8 172.217.43.3#45515 (wiki.forth-ev.de): query: wiki.forth-ev.de IN A -E(0)DC (5.45.109.212) [ECS 144.168.164.0/24/0]
14-Jun-2020 15:19:21.220 client @0x6c70a4e8 8.0.38.13#6642 (wiki.forth-ev.de): query: wiki.forth-ev.de IN AAAA -E(0)DC (5.45.109.212)
14-Jun-2020 15:19:21.227 client @0x6c70a4e8 172.217.44.3#39625 (wiki.forth-ev.de): query: wiki.forth-ev.de IN A -E(0)DC (5.45.109.212) [ECS 144.168.164.0/24/0]
14-Jun-2020 15:19:21.312 client @0x6c70a4e8 8.0.38.1#14944 (swappy.forth-ev.de): query: swappy.forth-ev.de IN AAAA -E(0)DC (5.45.109.212)
14-Jun-2020 15:19:22.112 client @0x6c70a4e8 172.217.43.4#57954 (ns8.dnssec.works): query: ns8.dnssec.works IN A -E(0) (5.45.109.212) [ECS 144.168.164.0/24/0]
14-Jun-2020 15:19:22.159 client @0x6c70a4e8 8.0.38.131#56466 (ns8.dnssec.works): query: ns8.dnssec.works IN A -E(0)DC (5.45.109.212)

```

It is just the normal BIND 9 query-log format, no special debug logging level required.

Can you send me a snippet of your log file that will cause the runtime error? A short file with a few lines will be enough. Please replace any sensitive information in the log such as IP addresses or domain names.

**Comment by mtheofy** [comment]
@cstrotm 

here's an indicative extract

```22-Sep-2020 23:19:04.552 queries: info: client @0x6cf1f868 192.168.1.64#64455 (profile.accounts.firefox.com): query: profile.accounts.firefox.com IN AAAA + (192.168.1.9)
22-Sep-2020 23:19:04.642 queries: info: client @0x6d2eefe0 192.168.1.64#58748 (identity.bitwarden.com): query: identity.bitwarden.com IN AAAA + (192.168.1.9)
22-Sep-2020 23:19:04.722 queries: info: client @0x67f8a618 fdff:8888:aaaa:dddd:955f:56b6:6e39:fed9#51668 (profile.accounts.firefox.com): query: profile.accounts.firefox.com IN A + (fdff:8888:aaaa:dddd:ba27:ebff:fec1:5b35)
22-Sep-2020 23:19:04.722 queries: info: client @0x67d47c88 fdff:8888:aaaa:dddd:955f:56b6:6e39:fed9#64455 (profile.accounts.firefox.com): query: profile.accounts.firefox.com IN AAAA + (fdff:8888:aaaa:dddd:ba27:ebff:fec1:5b35)
22-Sep-2020 23:19:04.932 queries: info: client @0x6d15fc80 192.168.1.64#52841 (profile.accounts.firefox.com): query: profile.accounts.firefox.com IN A + (192.168.1.9)
22-Sep-2020 23:19:05.212 queries: info: client @0x6d2eefe0 192.168.1.64#50490 (notifications.bitwarden.com): query: notifications.bitwarden.com IN A + (192.168.1.9)
22-Sep-2020 23:19:05.212 queries: info: client @0x6d15fc80 192.168.1.64#64194 (notifications.bitwarden.com): query: notifications.bitwarden.com IN AAAA + (192.168.1.9)
22-Sep-2020 23:19:05.312 queries: info: client @0x6d15fc80 192.168.1.64#60110 (notifications.bitwarden.com): query: notifications.bitwarden.com IN AAAA + (192.168.1.9)
22-Sep-2020 23:19:05.312 queries: info: client @0x68dcce38 192.168.1.64#63057 (notifications.bitwarden.com): query: notifications.bitwarden.com IN A + (192.168.1.9)
22-Sep-2020 23:19:05.382 queries: info: client @0x6cf1f868 192.168.1.65#44020 (www.google.com): query: www.google.com IN A + (192.168.1.9)
22-Sep-2020 23:19:05.392 queries: info: client @0x6d2eefe0 192.168.1.65#29366 (www.google.com): query: www.google.com IN AAAA + (192.168.1.9)
22-Sep-2020 23:19:05.642 queries: info: client @0x6d2eefe0 192.168.1.64#60580 (_ldap._tcp.pdc._msdcs.athens.private): query: _ldap._tcp.pdc._msdcs.athens.private IN SRV + (192.168.1.9)
22-Sep-2020 23:19:07.102 queries: info: client @0x6d2eefe0 192.168.1.64#63956 (in.appcenter.ms): query: in.appcenter.ms IN A + (192.168.1.9)
22-Sep-2020 23:19:07.102 queries: info: client @0x6d2ece58 192.168.1.64#51216 (in.appcenter.ms): query: in.appcenter.ms IN AAAA + (192.168.1.9)
22-Sep-2020 23:19:07.372 queries: info: client @0x67d47c88 fdff:8888:aaaa:dddd:955f:56b6:6e39:fed9#63956 (in.appcenter.ms): query: in.appcenter.ms IN A + (fdff:8888:aaaa:dddd:ba27:ebff:fec1:5b35)
22-Sep-2020 23:19:07.372 queries: info: client @0x67f8a618 fdff:8888:aaaa:dddd:955f:56b6:6e39:fed9#51216 (in.appcenter.ms): query: in.appcenter.ms IN AAAA + (fdff:8888:aaaa:dddd:ba27:ebff:fec1:5b35)
```

I notice that I have queries:info piece of text in the log. Might be that or the use of IPv6

**Comment by mtheofy** [comment]
Just noticed - in my named configuration I used

```        channel "querylog" {
                file "/var/log/named/query.log" versions 3 size 10m;
                severity debug 2;
                print-time yes;
                print-severity yes;
                print-category yes;
```

Tonight, I will try generating some logs using `print-severity: no;` and `print-category: no`

**Comment by cstrotm** [comment]
Hi @mtheophy 

thanks for the log snippets. I will test and report.

print-severity and print-category could be the problem, I that is the problem I'mm make the tool more robust to handle these different settings.

**Comment by cstrotm** [comment]
Hi @mtheophy 

when I run your test log snippet against the tool, it works without issues:

```
~/src/logeater$ ./logeater-queries -s < test.log 
Query-Statistics

15 : total queries ( 100 % )
0 : iterative queries ( 0 % )
15 : recursive queries ( 100  % )
0 : queries over TCP ( 0  % )
0 : queries with EDNS support ( 0  % )
0 : queries indicate DNSSEC support ( 0  % )
0 : queries with DNSSEC validation disabled (CD-flag) ( 0  % )
0 : queries TSIG signed ( 0  % )

~/src/logeater$ ./logeater-queries -d < test.log 
Query-Domain-Names

4 : notifications.bitwarden.com
4 : in.appcenter.ms
3 : profile.accounts.firefox.com
2 : www.google.com
1 : identity.bitwarden.com
1 : _ldap._tcp.pdc._msdcs.athens.private

~/src/logeater$ ./logeater-queries -c < test.log 
Query-Network-Classes

15 : IN

~/src/logeater$ ./logeater-queries -i < test.log 
Query-IP-Addresses

9 : 192.168.1.64 []
4 : fdff:8888:aaaa:dddd:955f:56b6:6e39:fed9 []
2 : 192.168.1.65 []

```

Can you please test the log-snippet that you've send locally on your side and post here the output from the terminal?

**Comment by mtheofy** [comment]
Hi @cstrotm,

I retested by deleting the previous query log file and generated a new from scratch. It worked as expected! 

I guess it must be a particular log entry that causes the issue, I will leave the query log on for sometime and retest. If the issue reappears, if you I agree, I will sent you the full log.

What do you think?

**Comment by cstrotm** [comment]
Hi @mtheophy 

sure. Please make first contact via support@menandmice.com and reference this issue (or a new github issue) and my name (Carsten Strotmann) and I will be able to provide you with a private, secure way to upload the log-file.

Greetings

Carsten
